title: Gabriel Godoy | Front-end Developer
email: hi@gabrielgodoy.com
description: > # this means to ignore newlines until "baseurl:"
  Sou apaixonado pela web e por novas tecnologias. Não existe nada mais dinâmico que a internet. É um desafio se manter atualizado com tantas coisas novas surgindo todos os dias, mas um desafio gratificante. Aprender coisas novas se torna um hábito diário para mim.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gabrielgodoy.com" # the base hostname & protocol for your site
twitter_username: g4brielgodoy
github_username:  gabrielgodoy

# Build settings
markdown: kramdown
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby']
