title: Gabriel Godoy
email: hi@gabrielgodoy.com
description: > # this means to ignore newlines until "baseurl:"
  I am passionated about the web and for new technologies. There is nothing more dynamic than the web, and that is why learning new things becomes a daily habit for me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gabrielgodoy.com" # the base hostname & protocol for your site
twitter_username: g4brielgodoy
github_username:  gabrielgodoy

# Build settings
markdown: kramdown
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

links:
  - title: blog
    url: /
  - title: about
    url: /about
  - title: projects
    url: /projects
  - title: Tags
    url: /tags

exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby', 'gulpfile.js']
